# Generated by Django 4.2.5 on 2023-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar2', '0003_product_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
