# Generated by Django 4.2.5 on 2023-09-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar3', '0003_post_showed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar3.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar3.author')),
            ],
        ),
    ]
