# Generated by Django 4.2.5 on 2023-09-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar3', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='post',
        ),
    ]
