# Generated by Django 4.2.5 on 2023-09-26 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seminar3', '0005_rename_article_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
